version: "3.1"
services:
    www:
        build: .
        ports: 
            - ${WWW_PORT}:80
        volumes:
            - ./docker/www/:/var/www/html/
        links:
            - db:db
        networks:
            - default
    db: # This service *must* be called 'db'
        image: mariadb:10.1
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
        volumes:
            - ./docker/dump:/docker-entrypoint-initdb.d
            - ./docker/conf:/etc/mysql/conf.d
            - ./docker/mysql:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - ${PMA_PORT}:80
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 